# Generated by Django 5.1.11 on 2025-06-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('episode_id', models.IntegerField()),
                ('opening_crawl', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('producers', models.CharField(max_length=250)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('climate', models.CharField(blank=True, max_length=100)),
                ('terrain', models.CharField(blank=True, max_length=100)),
                ('population', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('films', models.ManyToManyField(related_name='characters', to='core.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='planets',
            field=models.ManyToManyField(related_name='films', to='core.planet'),
        ),
    ]
